# Example settings file.
#
# @package   ApiOpenStudioAdmin
# @license   This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
#            If a copy of the MPL was not distributed with this file,
#            You can obtain one at https://mozilla.org/MPL/2.0/.
# @author    john89 (https://gitlab.com/john89)
# @copyright 2020-2030 Naala Pty Ltd
# @link      https://www.apiopenstudio.com

debug:
  formatters:
    api_open_studio_admin:
      format: "%datetime%-%channel%.%level_name% - %message%\n"
  handlers:
    console:
      class: Monolog\Handler\StreamHandler
      level: DEBUG
      formatter: api_open_studio_admin
      processors: [memory_processor]
      bubble: true
      stream: php://stdout
    admin_file_handler:
      class: Monolog\Handler\StreamHandler
      level: INFO
      formatter: api_open_studio_admin
      bubble: true
      stream: /var/www/html/logs/apiopenstudio_admin/error.log
  processors:
    web_processor:
      class: Monolog\Processor\WebProcessor
    memory_processor:
      class: Monolog\Processor\MemoryUsageProcessor
  loggers:
    admin:
      handlers: [admin_file_handler]
      processors: [web_processor]

admin:
  url: "admin.apiopenstudio.local"
  api_url: "api.apiopenstudio.local"
  protocols:
    - https
  core_account: apiopenstudio
  core_application: core
  base_path: "/var/www/html/admin/"
  dir_tmp: "/tmp/"
  dir_public: "public/"
  pagination_step: 20
  templates: "includes/templates/"
  slim:
    displayErrorDetails: true
    determineRouteBeforeAppMiddleware: true

twig:
  options:
    cache_enabled: true
    cache_path: "twig_cache/"
    debug: false
  template_path: "includes/templates/"
